### ISSUE TITLE
Possible feature: work with Vue-router?

### ISSUE THREAD

**Issue by Calvinv99** [edgardleal/require-vuejs#1]
Hi,

I twas wondering if you can add in this feature to extract the vue!components for vueRouter purposes?

Regards
Calv99

**Comment by edgardleal** [comment]
Hi Calvinv99. Thank you for your feed back.
I can't understand, can you send me an example ?

**Comment by edgardleal** [comment]
I include a new example using vue-router.
Check this example if is what you want:
https://github.com/edgardleal/require-vuejs/blob/master/examples/demo/app.js
