### ISSUE TITLE
Docs: configuration for r.js

### ISSUE THREAD

**Issue by razbakov** [edgardleal/require-vuejs#12]
I executed: 
```
r.js -o build.js
```

I have got an error:
```
Error: ENOENT: no such file or directory, open 'somefile.js'
In module tree:
    somemodule
      vue
```

Should I place `vue` in `exclude` or define with `empty:` in paths?
Neither of it works.

**Comment by edgardleal** [comment]
You should define a path named to **vue** pointing to require-vuejs file.

Note that this should be **vue** not **Vue**.

```
    requirejs.config({
        paths: {
            "Vue": "https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.min",
            "vue": "https://rawgit.com/edgardleal/require-vue/master/dist/require-vuejs"
        },
        shim: {
            "Vue": {"exports": "Vue"}
        }
    });
```

**Comment by razbakov** [comment]
This part is clear. I noticed it. Your example is requirejs config.
I mean r.js optimizer config.

**Comment by edgardleal** [comment]
I recommend you to create a optimizer config only for `r.js` .

**Comment by razbakov** [comment]
Sure, that's 2 different configuration. 
Everything works perfect with requirejs.
But I also have assets generation, where optimizer have to run.
I have problem with optimizer configuration. 
You can find error in description of this issue.

**Comment by edgardleal** [comment]
I am make some tests with examples and tell you when I finish this.

**Comment by edgardleal** [comment]
Sorry, I see now that you have an build.js file. 
Can you show me this content of this file ?

**Comment by edgardleal** [comment]
I need to change the `grunt` build. But now, its seems ok.

I included this file o `example/` folder [build.js](https://github.com/edgardleal/require-vuejs/blob/master/examples/build.js), but remember to not use cdn with `build.js`, all files should be on disk.
