### ISSUE TITLE
vue aliases in require-config

### ISSUE THREAD

**Issue by razbakov** [edgardleal/require-vuejs#13]
Is it possible to define aliases for vue components in `require-config`?

For example:

`require-config`:
```
paths: {
    'grid': 'ui/vue/grid'
}
```

`main.js`:
```
define(['vue!grid'], function (Grid){
Vue.component('grid', Grid);
...
})

**Comment by edgardleal** [comment]
Not now, but I will check on requirejs documentation if is possible to get the path for an alias.

**Comment by razbakov** [comment]
Thank you!

**Comment by edgardleal** [comment]
This functionality is ready on branch `develop`.
See the example [here](https://github.com/edgardleal/require-vuejs/blob/develop/examples/app.js)
