### ISSUE TITLE
PRE tag in  Template

### ISSUE THREAD

**Issue by artyprog** [edgardleal/require-vuejs#17]
Hy,

In "template "tags, the "pre" tag does not preserve lines feed.
All text  is displayed in one line....
I would like to display highlighted code

Regards

**Comment by edgardleal** [comment]
Can you give me an example ?

**Comment by artyprog** [comment]
Yes of course 
Here is a sample : [http://vuejsrequire-prebug.surge.sh/](http://vuejsrequire-prebug.surge.sh/).

Regards

**Comment by edgardleal** [comment]
I am working on it.

**Comment by edgardleal** [comment]
I fixed it on this commit d75fd25329f06beb575acc26afdb15b45144b51c 
I need fix more things to generate an release.
