### ISSUE TITLE
VueJS Version

### ISSUE THREAD

**Issue by artyprog** [edgardleal/require-vuejs#18]
Hello,

Have you tried to use the latest version of Vue ?
All seem ok until the 2.3.4 version, It must be a problem with requirejs

When I use the latest version, here is the error

TypeError: t is undefined[En savoir plus]  vue.min.js:6:7661
	ct https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js:6:7661
	lt/l< https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js:6:8122
	C/< https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js:6:1978
	newContext/context.execCb http://localhost:9999/Scripts/Audit/require.js:1696:24
	newContext/Module.prototype.check http://localhost:9999/Scripts/Audit/require.js:883:43
	newContext/Module.prototype.enable/</< http://localhost:9999/Scripts/Audit/require.js:1139:29
	bind/< http://localhost:9999/Scripts/Audit/require.js:134:20
	newContext/Module.prototype.emit/< http://localhost:9999/Scripts/Audit/require.js:1189:21
	each http://localhost:9999/Scripts/Audit/require.js:59:31
	newContext/Module.prototype.emit http://localhost:9999/Scripts/Audit/require.js:1188:17
	newContext/Module.prototype.check http://localhost:9999/Scripts/Audit/require.js:938:25
	newContext/Module.prototype.enable http://localhost:9999/Scripts/Audit/require.js:1176:17
	newContext/Module.prototype.init http://localhost:9999/Scripts/Audit/require.js:788:21
	newContext/Module.prototype.callPlugin/</< http://localhost:9999/Scripts/Audit/require.js:982:33
	bind/< http://localhost:9999/Scripts/Audit/require.js:134:20
	newContext/Module.prototype.emit/< http://localhost:9999/Scripts/Audit/require.js:1189:21
	each http://localhost:9999/Scripts/Audit/require.js:59:31
	newContext/Module.prototype.emit http://localhost:9999/Scripts/Audit/require.js:1188:17
	newContext/Module.prototype.check http://localhost:9999/Scripts/Audit/require.js:938:25
	newContext/Module.prototype.enable http://localhost:9999/Scripts/Audit/require.js:1176:17
	newContext/Module.prototype.init http://localhost:9999/Scripts/Audit/require.js:788:21
	newContext/Module.prototype.callPlugin/</load< http://localhost:9999/Scripts/Audit/require.js:1014:25
	bind/< http://localhost:9999/Scripts/Audit/require.js:134:20
	newContext/context.execCb http://localhost:9999/Scripts/Audit/require.js:1696:24
	newContext/Module.prototype.check http://localhost:9999/Scripts/Audit/require.js:883:43
	newContext/Module.prototype.enable http://localhost:9999/Scripts/Audit/require.js:1176:17
	newContext/Module.prototype.init http://localhost:9999/Scripts/Audit/require.js:788:21
	localRequire/<

**Comment by edgardleal** [comment]
@artyprog I can't reproduce this error here using `vuejs 2.3.4` and `requirejs 2.3.3`.
If you can, please send me the requirejs configuration for Vue dependency. It seems that is an error while try to load vuejs dependency by requirejs.

**Comment by artyprog** [comment]
Hy Edgard

Here is the config

```javascript

var baseUrl = "Scripts/Audit";

//baseUrl = prompt("BaseUrl ?")

requirejs.config({
    baseUrl: baseUrl,
    paths: {
        "Vue": "https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.4/vue.min",
        "vue": "https://rawgit.com/edgardleal/require-vue/master/dist/require-vuejs",

        'text': './lib/text',
        'print': './lib/print'     
    }
});



function registerAsyncComp(compname, filename) {
    require(["Vue"], function (Vue) {
        Vue.component(compname, resolve => {
            require([filename], resolve)
        })
    })
}

registerAsyncComp('my-app', 'vue!Components/app.html');
registerAsyncComp('my-creer', 'vue!Components/creer.html');
registerAsyncComp('my-missionner', 'vue!Components/missionner.html');
registerAsyncComp('my-fixerdate', 'vue!Components/fixerdate.html');
registerAsyncComp('my-planaudit', 'vue!Components/planaudit.html');
registerAsyncComp('my-redigercr', 'vue!Components/redigercr.html');
registerAsyncComp('my-evalueraudit', 'vue!Components/evalueraudit.html');
registerAsyncComp('my-clotureraudit', 'vue!Components/clotureraudit.html');


requirejs(['application/main']);
```

**Comment by edgardleal** [comment]
I cant reproduce the error on this folder https://github.com/edgardleal/require-vuejs/blob/develop/examples/demo/ .

The method `registerAsyncCom` should be called after `application/main` inside an event like a button click or a url change.

Your code also could be like this: 
```js

requirejs([
        'vue!Components/app.html',
        'vue!Components/creer.html',
        'vue!Components/missionner.html',
        'vue!Components/fixerdate.html',
        'vue!Components/planaudit.html',
        'vue!Components/redigercr.html',
        'vue!Components/evalueraudit.html',
        'vue!Components/clotureraudit.html',
        
        'application/main']);
```

PS: In this case, each componente file ( Ex.: `components/app.html` ) should register it self calling `Vue.component` method.

PS[1] : To use async dependencies with vue-router see this example: https://github.com/edgardleal/require-vuejs/blob/develop/examples/demo/app.js

Let me know if you can solve this problem or if you have any sugestion.

**Comment by artyprog** [comment]
Thank you Edgar,

I will follow your advices
You can close this issue.

Regards
