### ISSUE TITLE
Is it possible to use a inner template within a template?

### ISSUE THREAD

**Issue by daewooLeeNy** [edgardleal/require-vuejs#21]
It is possible to use v-if with <template> in <template>.
(<template v-if = "true"> </ template>) There is a problem that the tag after the inner template does not render normally.

I modified some code on the component to reproduce the phenomenon 
```
<template>
    <div>
        <h1> {{text}} </h1>

        <template v-if="true">
            <div> Inner template</div>
        </template>

        <div>It is not shown</div>
    </div>
</template>
```
Finally love your work!

**Comment by edgardleal** [comment]
It is possible, and I thing that it already work, but I recommend you to use `v-if` directly on `div` tag like this:

```
<template>
    <div>
        <h1> {{text}} </h1>

            <div v-if="true"> Inner template</div>

        <div>It is not shown</div>
    </div>
</template>
```

**Comment by daewooLeeNy** [comment]
@edgardleal Thanks your comment.
But in case of `<div>` has a custom style,  'div v-if' some effect for render.

So i need to use a inner `<template> `tag.

custom style like this:
```
<template>
    <div>
        <h1> {{text}} </h1>

        <template v-if="true">
            <div> Inner template</div>
        </template>

        <div>It is not shown</div>
    </div>
</template>

<style>
.div {
  padding: 1px;
}
</style>
```

**Comment by edgardleal** [comment]
See this example of code base on your example: 
https://jsfiddle.net/2qk1j73v/

Make any change on it and post hear to make me understand better this problem.

**Comment by daewooLeeNy** [comment]
@edgardleal My example was not sufficiently.

And in the master version, I found that the phenomenon can not be reproduced.

Please see and check for my code in forked repository.
https://github.com/daewooLeeNy/require-vuejs/tree/inner-template-not-work/examples/inner_template_not_work

**Comment by edgardleal** [comment]
I did not know it worked.
I tried your code and see that the `div` after inner template don't appear.

After render, Vuejs create your component content in a virtual document, and this virtual `document` ( from current browser ) remove all tags the it dont recognize, like `<template>` and I think it is removing every thing after inner tag `template`.

I dont understand yet why not use `v-for` inside the `div` tag.

I tested your code with `v-for` inside the div and it seems good for me: 

![](https://i.imgur.com/INYCyow.png)


```html
<template>
    <div>
        <h1> {{text}} </h1>
        <p class="checkpoint">Please check the named '.not-work' tag will be shown</p>

            <div v-for="v in numbers"> {{v}} Inner template</div>

        <div class='not-work'>This tag not work after inner template</div>
    </div>
</template>

<script>
define(["Vue"], function(Vue) {
    Vue.component("my-component", {
        template: template,
        data: function() {
            return {
                "text": "component.vue",
                "numbers": [1,2,3,4]
            };
        }
    });
});
</script>

<style>
div {
    border: 1px solid;
}
.checkpoint {
  color: red
}
.not-work {
  color: blue
}
</style>

```

**Comment by daewooLeeNy** [comment]
Thanks for your work.
I think that '<template v-for|v-if>' is general usage.
(For this reason I have spent a time looking for other ways.)

> https://vuejs.org/v2/guide/conditional.html#Conditional-Groups-with-v-if-on-lt-template-gt
> https://vuejs.org/v2/guide/list.html#v-for-on-a-lt-template-gt

**Comment by edgardleal** [comment]
The newest version [1.0.1](https://github.com/edgardleal/require-vuejs/releases/tag/1.1.0) is ready to use inner templates.
You can see an example [here](https://github.com/edgardleal/require-vuejs/blob/master/examples/demo/inner_template.vue)

I am closing this issue. If you have any problem fell free to reopen this issue or create other.
Thank for your participation on this project!
