### ISSUE TITLE
How to use router-vue.js

### ISSUE THREAD

**Issue by Lospepes** [edgardleal/require-vuejs#23]
Hello,

I'm trying to use the router-vue but I have some problems to dynamically load the right component. Would you have any advice for me, please?

I have something that works without require-vue, I don't find how to import my vue file into my components routes !

`requirejs.config({
    paths: {
        "Vue": "./js/libraries/vue",
        "vue": "./js/libraries/require-vuejs",
        "VueRouter": "./js/libraries/vue-router"
    },
    shim: {
        "Vue": {"exports": "Vue"}
    }
});

require(["Vue", "VueRouter", 'vue!./components/test.vue', 'vue!./components/HelloWorld.vue'], function(Vue, VueRouter){

	const router = new VueRouter({
								routes : [
									{
										path: '/',
										name: 'test',
										component:  { template: '<div>foo</div>', name: 'test'}
									},
									{
										path: '/hello',
										name: 'hello',
										component: { template: '<div>bar</div>', name: 'hello'}
									}
								]
							})

	Vue.use(VueRouter);

	const app = new Vue({
		router
    }).$mount('#app');
});`

Thank you in advance

**Comment by edgardleal** [comment]
Try this code and tell me if it works for you.

```js
require(["Vue", 
     "VueRouter", 
     'vue!./components/test.vue', 
     'vue!./components/HelloWorld.vue'], 
   function(Vue, VueRouter, Test, HelloWorld) {

  const router = new VueRouter({
    routes: [{
      path: '/',
      name: 'test',
      component: Test
    }, {
      path: '/hello',
      name: 'hello',
      component: HelloWorld
    }]
  })

  Vue.use(VueRouter);

  const app = new Vue({
    router
  }).$mount('#app');
});
```

**Comment by Lospepes** [comment]
Thank you for your answer !

I tried to access my components like this and they are undefined ! With your code too :)

**Comment by edgardleal** [comment]
Post the code of your component and I will try it with your code.

**Comment by Lospepes** [comment]
I made a clean archive. I hope I didn't add mistakes ! Thank you

I like your code, It will avoid me to build with node !






[app.zip](https://github.com/edgardleal/require-vuejs/files/1593218/app.zip)

**Comment by edgardleal** [comment]
In your code you are registering yours components internally using `Vue.component('name', object)`.
I recomend you to export your component as plain object like this:
```js
	define(["Vue"], function(Vue) {
		var component = {
			template: template,
			data: function() {
				return {"msg": "Ok"};
			}
		};
               Vue.component("my-component", component);
                return component;
	});
```

Now you can use with your current code, and with vue-router too.

**Comment by Lospepes** [comment]
Thanks a lot @edgardleal, it works !
