### ISSUE TITLE
Uncaught TypeError: plugin.load is not a function

### ISSUE THREAD

**Issue by ogardiazabal** [edgardleal/require-vuejs#25]
A difficult to reproduce error on the first `require(["vue!" + path]);` when the cdn of requirejs-vue takes too long to load but finally loads.

my require.config looks like this:
```
require.config({
    waitSeconds: 0,
    paths: {
        jquery: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery",
        Vue: "https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue",
        vue: 'https://cdn.rawgit.com/edgardleal/require-vuejs/aeaff6db/dist/require-vuejs',
        router: "../src/router/index"
    },
    shim: {
        router: ["jquery", "Vue", "vue"],
    }
});

require(['Vue'], function (vue2) {
    window.Vue = vue2;
});

require([
    "jquery",    
    "Vue",
    "vue",
    "router"
]);
```

Has anyone already had this issue?

**Comment by oscar-gardiazabal** [comment]
A bunch of loading issues like that goes away when I **change** the vue **path name** from this:
```
requirejs.config({
    paths: {
        [...]
        "vue": "https://cdn.rawgit.com/edgardleal/require-vuejs/aeaff6db/dist/require-vuejs",
    }
});
```
to something like this:
```
requirejs.config({
    paths: {
        [...]
        "require-vuejs": "https://cdn.rawgit.com/edgardleal/require-vuejs/aeaff6db/dist/require-vuejs",
    }
});
```
and **requiring** vue components in the **same way**: 
```
require(["vue!" + url], function (component) {
    [...]
});
```
There is a **conflict** between **"vue"** names in **requirejs** load/build?

**Comment by edgardleal** [comment]
Good point. I will make some tests to find out what is happening.

**Comment by oscar-gardiazabal** [comment]
great!

**Comment by oscar-gardiazabal** [comment]
sry my fault, 
**Material Design Bootstrap** (https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.5/js/mdb) has incompatibilities with **requirejs** and random errors fires when **require-vuejs** loads first component.
mdbootstrap/bootstrap-material-design#135
