### ISSUE TITLE
require-vue not working when run cordova app in IOS

### ISSUE THREAD

**Issue by ksankumar** [edgardleal/require-vuejs#26]
Everything working fine except IOS.

Error: Load timeout for modules: vue!components/test.vue_unnormalized2,vue!components/test.vue
http://requirejs.org/docs/errors.html#timeout
```

var asyncComp = function (componentName) {
        return function (resolve) {
            require([componentName], resolve);
        };
    };
       
       
    var router = new VueRouter({
        routes: [
            {path: "", name: test", component: asyncComp("vue!components/test")}
                
        ]
    });
```

**Comment by oscar-gardiazabal** [comment]
Have you tried to remove the timeout of require.js?
```
require.config({
    waitSeconds: 0,
    [...]
});
```

**Comment by ksankumar** [comment]
Yes. I tried with out waitSeconds, and with waitSeconds:0 to 5 as well.

But no luck

If i sets waitSeconds:0 i didn't get timeout error and component also not get load

**Comment by ksankumar** [comment]
**home.vue**
```
<template>
    <h3>Hello world</h3>
</template>

<script>
    define(["Vue"], function (Vue) {
        return Vue.component("home", {
            template: template
        });
    });
</script>
```
**main.js**
```
(function() {
    require.config({
        waitSeconds: 0,
        paths: {
            "Vue": "js/lib/vue",
            "vue-router": "js/lib/vue-router.min",
            "vue": "js/lib/require-vuejs.min"
        },
        shim: {
            "Vue": { exports: "Vue" }
        }
    });
    require(["Vue", "vue-router"],
        function(Vue, VueRouter) {

            Vue.use(VueRouter);
            var asyncComp = function(componentName) {
                return function(resolve) {
                    require([componentName], resolve);
                };
            };
            var router = new VueRouter({
                routes: [
                    { path: "", name: "home", component: asyncComp("vue!home") },
                ]
            });

            new Vue({
                el: '#app-container',
                router: router
            });
        });
})();
```

When run this app in cordova, home.vue not loading

**Comment by ksankumar** [comment]
Atlast i tried with below mentioned alternative vue component loader and worked fine with cordova ios.

https://github.com/vikseriq/requirejs-vue/blob/master/requirejs-vue.js

**Comment by ksankumar** [comment]
@edgardleal 

I found the issue in your code which is making http call for pulling vue component

```
if (xhttp.readyState === 4 && this.status < 400) {
              callback(parse(xhttp.responseText));
}
```

Change **this**.readystate to **xhttp**.readyState.

this.readyState causing issue in ios hybrid app(cordova).

**Comment by edgardleal** [comment]
[@ksankumar](https://github.com/ksankumar)

What version are you using ? 

In current release on line [L226](https://github.com/edgardleal/require-vuejs/blob/master/dist/require-vuejs.js#L226) the code is different, it is using `this` because it is on `xhttp` function scope. To avoid any king of problem i changed it now.

Can you send the error message ? 
Do you know any good ( and simple ) template for **cordova** to include on this project examples ( and it will help me to make more tests ) ?

**Comment by ksankumar** [comment]
@edgardleal 

I am using very current version what you have.  Issue is in webview IOS returns the xhr status is 0, but you where checking either 200 or 304.(https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

100, 101, 102 < 200 These all status is Information response
304 not modified .

Your current commit also have same issue.

In IOS webview it won't return any issue, because in your code xhr don't have any timeout handling. 


Note:
we can check both way like **_this_** or **_xhttp_**

**readyState** only matter, **status** doesn't 

This is the correct fix.

`if(xhttp.readyState === 4 && xhttp.status < 400)`

or

`if(this.readyState === 4 && this.status < 400)`

or

`if (this.readyState === 4 && this.status === 200) `

or

`if (xhttp.readyState === 4 && xhttp.status === 200) `

**Comment by edgardleal** [comment]
If you want, you can use this version for now: [developer/require-vuejs.js](https://raw.githubusercontent.com/edgardleal/require-vuejs/develop/dist/require-vuejs.js) , but i steel working to improve timeout and general script handler.

**Comment by ksankumar** [comment]
Issue fixed
