### ISSUE TITLE
How to include css style when using r.js to combile the .vue files to one file?

### ISSUE THREAD

**Issue by qinbx** [edgardleal/require-vuejs#3]
Hi,

First thanks very much for this work. This helps me a lot.

In our project, we have style tag in .vue files, and we found our plugin not handle style code when using r.js to combile vue files to one file. (As below code)

```
    if(typeof document !== "undefined") {
            css_parser.parse(text);
        }
```

Do you know if there is an easy way to handle style code in this case?

Thanks a lot.

**Comment by edgardleal** [comment]
I am working in a way to improve the parser ( I will try to commit it today ).

I am embeding the code responsible to "mount" the css style in final page, but in future I will use the `Vue.compile` method to provide scoped style feature.

**Comment by edgardleal** [comment]
I implemented a temporary solution for styles.

**Comment by qinbx** [comment]
@edgardleal 
Cool. I will feedback once i have a chance to check. Thanks.
