### ISSUE TITLE
How I can load single file components

### ISSUE THREAD

**Issue by SalvatoreMazzullo** [edgardleal/require-vuejs#37]
I would need to be able to use components like this https://github.com/charliekassel/vuejs-datepicker

But I can not find the right way to do it.

**Comment by edgardleal** [comment]
Take a look at this example [Using with VuejsDatePicker](https://github.com/edgardleal/require-vuejs/wiki/Using-with-vuejs-datepicker)

Feel free to reopen this issue o create other issue if you have any question or if this example dont help.

**Comment by StratoKyke** [comment]
The package has been correctly imported.
Applying the same technique on this: https://github.com/DanSnow/vue-recaptcha
Not work...
