### ISSUE TITLE
Uncaught TypeError: extractCss(...).replace is not a function

### ISSUE THREAD

**Issue by ajgarrido** [edgardleal/require-vuejs#4]
I get this error with this latest pluggin update, in case you can correct it as soon as possible that your work is very good and I am using it for a project right now. Thank you

"Uncaught TypeError: extractCss(...).replace is not a function"

**Comment by edgardleal** [comment]
Sorry for this.
I solved this bug in the last commit.
If the problem continues, please let me know.
