### ISSUE TITLE
Tag for current master version

### ISSUE THREAD

**Issue by mzastue** [edgardleal/require-vuejs#40]
Hello, have you planning to create a tag for current master changes?
Currently the newest tag is 1.1.1 and then fix for Firefox came, but still with old tag.

Thanks!

**Comment by edgardleal** [comment]
Sorry for that. 
I accepted the pull request direct on master branch and this made me forget the correct flux of releases ( from dev to tag and master ).
I will create a new release to fix it and come back to correct release flux.

**Comment by mzastue** [comment]
@edgardleal sounds great. I see the tag is already created. So it could be close I think.
