### ISSUE TITLE
template tag in template section is not supported

### ISSUE THREAD

**Issue by razbakov** [edgardleal/require-vuejs#7]
Example code:

```
<template>
	<div id="div2">
              <template>{{text}}</template>
        </div>
</template>

<script>
    define(["Vue"], function(Vue) {
		console.log(" registering the component my-component2");
		Vue.component("my-component2", {
			template: template,
			data: function() {
				return {"text": "Ok from component.html"};
			}
		});
    });
</script>

<style>

div#div2 {
	border: 1px solid red;
}
</style>
```

It will throw en error, that template and dev tags are not closed.

**Comment by edgardleal** [comment]
Where did you use a tag `<template>` ( line 4 ) would not it be a `<slot>` ?

**Comment by razbakov** [comment]
See https://vuejs.org/v2/guide/conditional.html#Conditional-Groups-with-v-if-on-lt-template-gt

I need it in something like this:
 
```html
<template>
    <table>
    <template v-if="something">
        <tr>...</tr>
        <tr>...</tr>
     </template>
    <template v-else>
        <tr>...</tr>
        <tr>...</tr>
     </template>
    </table>
</template>
```

**Comment by edgardleal** [comment]
For now, you can use a simple `div` or `span` where you are using `template` with `v-if` with a minimum impact in your css style.

I will work in a solution for this and I will tell you when it is ready.

**Comment by razbakov** [comment]
I used this workaround already everywhere I could.
The problem is that it is not possible to use `div` and `span` inside `table`.

**Comment by razbakov** [comment]
@edgardleal can you please update `dist`?

**Comment by razbakov** [comment]
I added PR with updated `dist` files.
Can you please merge it and introduce a new release tag?
